apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spaces.k8spin.cloud
spec:
  scope: Namespaced
  group: k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - resources
                - containers
              properties:
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      users:
                        type: array
                        items:
                          type: string
                      serviceAccounts:
                        type: array
                        items:
                          type: string
                    required:
                      - name
                resources:
                  type: object
                  required:
                    - cpu
                    - memory
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                containers:
                  type: object
                  required:
                    - defaults
                  properties:
                    defaults:
                      type: object
                      required:
                        - resources
                      properties:
                        resources:
                          type: object
                          required:
                            - cpu
                            - memory
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                    enforce:
                      type: object
                      properties:
                        runtimeClassName:
                            type: string
                allowIncomingNetwork:
                  type: object
                  properties:
                    organizations:
                      type: array
                      items:
                        type: object
                        properties:
                          organization_name:
                            type: string
                        required:
                          - organization_name
                    tenants:
                      type: array
                      items:
                        type: object
                        properties:
                          organization_name:
                            type: string
                          tenant_name:
                            type: string
                        required:
                          - organization_name
                          - tenant_name
                    spaces:
                      type: array
                      items:
                        type: object
                        properties:
                          organization_name:
                            type: string
                          tenant_name:
                            type: string
                          space_name:
                            type: string
                        required:
                          - organization_name
                          - tenant_name
                          - space_name
  names:
    kind: Space
    plural: spaces
    singular: space
    shortNames:
      - spcs
      - sp
