apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/k8spin-webhook-cert
  name: validating-k8spin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "k8spin-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: validating.tenants.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /validator/tenants
      caBundle: Cg==
    rules:
      - apiGroups: ["k8spin.cloud"]
        resources:
          - "tenants"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
  - name: validating.spaces.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /validator/spaces
      caBundle: Cg==
    rules:
      - apiGroups: ["k8spin.cloud"]
        resources:
          - "spaces"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/k8spin-webhook-cert
  name: mutating-k8spin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "k8spin-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: mutating.organizations.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutator/organizations
      caBundle: Cg==
    rules:
      - apiGroups: ["k8spin.cloud"]
        resources:
          - "organizations"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
  - name: mutating.tenants.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutator/tenants
      caBundle: Cg==
    rules:
      - apiGroups: ["k8spin.cloud"]
        resources:
          - "tenants"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
  - name: mutating.spaces.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutator/spaces
      caBundle: Cg==
    rules:
      - apiGroups: ["k8spin.cloud"]
        resources:
          - "spaces"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
  - name: mutating.pods.k8spin.cloud
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    objectSelector:
      matchExpressions:
        - {key: application, operator: NotIn, values: [k8spin-webhook, k8spin-operator]}
    clientConfig:
      service:
        name: k8spin-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutator/pods
      caBundle: Cg==
    rules:
      - apiGroups: [""]
        resources:
          - "pods"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
