name: "Branch"

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: armv6
            distro: buster
          - arch: armv7
            distro: buster
          - arch: aarch64
            distro: buster
          - arch: ppc64le
            distro: buster

    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
        version: "v0.9.0"
        skipClusterCreation: "true"
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade virtualenv
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Available platforms
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Execute E2E tests
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
      run: |
        make test-e2e
    - name: Upload E2E logs
      continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: e2elogs
        path: e2elogs
